config/routes.rb
Rails.application.routes.draw do

  get "/home", to: 'static_pages#home'
  get "/about", to: 'static_pages#about'
  get "/help", to: 'static_pages#help', as: "helf"
  get "/contact", to: 'static_pages#contact'
  get "/signup", to: "users#new", as: "new_user"
  post "/signup",  to: 'users#create'
  get "/signin", to: 'sessions#new'
  post "/signin", to: 'sessions#create'
  delete "/signout", to: 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # root 'application#hello'
  root 'static_pages#home'

  # REST resources for GET POST PATCH DELETE
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  # needed for bcrypt
  has_secure_password # attr_accessor :password, :password_confirmation
  # callbacks
  before_save { self.email = email.downcase }
  before_save { self.first_name = first_name.downcase.capitalize}
  before_save { self.last_name = last_name.downcase.capitalize}
  # constants
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  # validations
  validates(:first_name, { presence: true, length: { in: 1..50 }})
  validates(:last_name, { presence: true, length: { in: 2..50 }})
  validates(:email, { presence: true , length: { maximum: 50 }, format:
  { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }})
  # allow_nil gives user the ability to leave pw blank upon editing profile
  validates(:password, presence: true, length: { minimum: 6 }, allow_nil: true)

  # combine first_name and last_name attributes into a full name string
  def full_name
    "#{first_name} #{last_name}"
  end

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

 # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # use fail to dump params hash to the browser
  protect_from_forgery with: :exception
  include SessionsHelper

  # test hello as root to make sure Heroku deployment is successful
  # def hello
    # render html: "Hello, world"
  # end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      login(user)
      flash[:success] = "Boom! Welcome back, #{user.first_name}."
      redirect_to user_path(user)
    else
      # render is not a new request like redirect_to, therefor we use flash.now
      # so the flash only shows up once.
      flash.now[:danger] =
      "Doh! Looks like that email/password combo is incorrect"
      render 'new'
    end
  end

  def destroy
    logout
    flash[:success] = "You've signed out! See you again soon."
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  # use fail to dump params hash to the browser
  def home
  end

  def about
  end

  def help
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # use fail to dump params hash to the browser

  # GET
  def show
    respond_to do |format|
      format.html { @user = User.find(params[:id]) }
    end
  end

  # GET
  def new
    @user = User.new
  end

  # POST
  def create
    @user = User.create(user_params)
    if @user.save
      flash[:success] = "Welcome to the application, #{@user.first_name}!"
      redirect_to user_path(@user)
      login(@user)
    else
      render 'new'
    end
  end

  # GET
  def show
    @user = User.find(params[:id])
  end

  # PATCH isn't natively sent via browser, so use POST

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Your profile changes have been successfully made!"
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

  private

  # used to enable explicit assignment of attributes via mass assignment
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password,
                                 :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # renders the full title via <% provide(:title, "Something") %>
  def full_title(title)
    base_title = "Ruby on Rails Tutorial"
    if title.empty?
      base_title
    else
      "#{title} | Ruby on Rails Tutorial"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Using the session method, we can securely place a user id on the browser
  # to create a temporary session.
  # Logs in a user with a temp cookie in the session hash
  def login(user)
    session[:user_id] = user.id
  end

  # Logs out a user by removing temp cookie in session hash
  def logout
    # session.delete(:user_id) does the same thing
    session[:user_id] = nil
  end

  # unlike self.find, self.find_by doesn't raise an exception if the user_id
  # doesn’t exist, simply returns nil
  # storing the result of User.find_by in an instance variable,
  # which hits the database the first time but returns the instance variable
  # immediately on subsequent invocations

  # returns the current user (if any) via session id
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, size: 120)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.first_name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path() %></li>
      <li><%= link_to "Contact", contact_path() %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path() %></li>
        <li><%= link_to "Help", helf_path() %></li>
        <% if logged_in? %>
         <li><%= link_to "Users", '#' %></li>
         <li class="dropdown">
           <a href="#" class="dropdown-toggle" data-toggle="dropdown">
             Account <b class="caret"></b>
           </a>
           <ul class="dropdown-menu">
             <li><%= link_to "Profile", user_path(current_user) %></li>
             <li><%= link_to "Settings", edit_user_path(current_user) %></li>
             <li class="divider"></li>
             <li>
               <%= link_to "Log out", signout_path, method: :delete %>
             </li>
           </ul>
         </li>
       <% else %>
         <li><%= link_to "Log in", signin_path %></li>
       <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    <%= render 'layouts/footer' %>
    <!-- display YAML representation of debug information in the development
        environment only -->
    <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      Doh! Your submission contains
      <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  The <a href="http://www.railstutorial.org/"><em>Ruby on Rails
  Tutorial</em></a> is a
  <a href="http://www.railstutorial.org/book">book</a> and
  <a href="http://screencasts.railstutorial.org/">screencast series</a>
  to teach web development with
  <a href="http://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://www.railstutorial.org/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="http://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>
  book</a>.
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to the Sample App</h1>

  <h2>
    This is the home page for the
    <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    sample application.
  </h2>

  <%= link_to "Sign up now!", new_user_path(), class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails logo"),
            'http://rubyonrails.org/' %>

app/views/users/edit.html.erb
<% provide(:title, 'Update account') %>
<h1>Update account information</h1>

<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <%= render 'shared/errors', object: @user %>
  </div>
  <div class="col-md-4 col-md-offset-4">
  <!-- @user already exists in the db (@user.new_record? returns false),
  so Rails knows this is a PATCH request -->
    <%= form_for(@user, url: user_path) do |form| %>
      <%= form.label :first_name, placeholder: "Johnny", required: true,
          autofocus: true %>
      <%= form.text_field :first_name %>

      <%= form.label :last_name, placeholder: "Appleseed", required: true %>
      <%= form.text_field :last_name %>

      <%= form.label :email, placeholder: "johnny@example.com",
                      required: true %>
      <%= form.email_field :email %>

      <%= form.label :password, required: true %>
      <%= form.password_field :password %>

      <%= form.label :password_confirmation, "Confirm your password", required: true %>
      <%= form.password_field :password_confirmation %>

      <!-- call method: :patch to be explicit -->
      <%= form.submit "Confirm updates",
                      class: "btn btn-primary", method: :patch %>
    <% end %>
    <br>
    <%= gravatar_for(@user) %>
    <p><a href="http://www.gravatar.com/emails", rel='noopener' target='_blank'>
        update gravatar</a></p>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <%= render 'shared/errors', object: @user %>
  </div>
  <div class="col-md-4 col-md-offset-4">

    <%= form_for(@user, url: new_user_path) do |form| %>
      <%= form.label :first_name, placeholder: "Johnny", required: true,
          autofocus: true %>
      <%= form.text_field :first_name %>

      <%= form.label :last_name, placeholder: "Appleseed", required: true %>
      <%= form.text_field :last_name %>

      <%= form.label :email, placeholder: "johnny@example.com",
                      required: true %>
      <%= form.email_field :email %>

      <%= form.label :password, required: true %>
      <%= form.password_field :password %>

      <%= form.label :password_confirmation, "Confirm your password", required: true %>
      <%= form.password_field :password_confirmation %>

      <%= form.submit "Create account", method: :post,
                      class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, "#{@user.first_name}") %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.first_name %>
      </h1>
    </section>
  </aside>
</div>